# Generated by Django 3.2.6 on 2022-02-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Type', 'verbose_name_plural': 'Types'},
        ),
        migrations.AlterModelOptions(
            name='website',
            options={'verbose_name': 'Website', 'verbose_name_plural': 'Websites'},
        ),
        migrations.AddField(
            model_name='website',
            name='image',
            field=models.ImageField(blank=True, upload_to='productColor gallery', verbose_name='Фото'),
        ),
    ]
