# Generated by Django 3.2.6 on 2022-03-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220306_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='link',
            field=models.TextField(null=True, verbose_name='Ссылка'),
        ),
    ]
